language: node_js

node_js:
  - "8"

env:
  - NODE_ENV=ci

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test:no-cache
  - npm run build:prod
  - npm run test:no-cache
