language: node_js

node_js:
  - "6"
  - "7"
  - "8"
matrix:
  - fast_finish: true
  allow_failures:
    - node_js: "8"
env:
  - NODE_ENV=ci

cache:
  directories:
  - node_modules

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run lint
  - npm run build
  - npm test
  - npm run build:prod
  - npm test
